
services:
  pyrite:
    container_name: pyrite
    image: garage44/pyrite:latest
    networks:
      - pyrite
    depends_on:
      - galene
    ports:
      - 3030:3030
    volumes:
      - ./pyrite/config/:/usr/app/config
      - ./galene/config/:/usr/app/galene

  galene:
    container_name: galene
    image: garage44/galene:0.5.0
    networks:
      - pyrite
    ports:
      - 8443:8443
    user: $PYRITE_UID:$PYRITE_GID
    volumes:
      - ./galene/config/data:/go/src/galene/data
      - ./galene/config/groups:/go/src/galene/groups
      - ./galene/config/recordings:/go/src/galene/recordings

networks:
  pyrite:
    driver: bridge

version: "3.8"
