services:
  galene:
    container_name: galene
    image: garage44/galene:latest
    volumes:
      - ./data:/go/src/galene/data
      - ./groups:/go/src/galene/groups
    ports:
      - 1194:1194
      - 8443:8443

