name: develop

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install packages & verify code
      run: |
        npm i
        npm run lint
    - name: Deploy (Beta)
      env:
        RAND_ENDPOINT: ${{secrets.RAND_ENDPOINT}}
        RAND_CHANNEL: ${{secrets.RAND_CHANNEL_DEVELOP}}
        RAND_PW: ${{secrets.RAND_PW}}
        RAND_USER: ${{secrets.RAND_USER}}
      run: VITE_VERSION=$(git rev-parse --short HEAD) npm run build
