name: main

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install packages & verify code
      run: |
        npm ci
        npm run lint
    - name: Deploy & Release (Production)
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        RAND_ENDPOINT: ${{secrets.RAND_ENDPOINT}}
        RAND_CHANNEL: ${{secrets.RAND_CHANNEL}}
        RAND_PW: ${{secrets.RAND_PW}}
        RAND_USER: ${{secrets.RAND_USER}}
      run: npx semantic-release
