name: test

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install packages & verify code
      run: |
        npm ci
        npm run lint
    - name: Release
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx semantic-release
    - name: Deploy artifacts
      env:
        RAND_HOST: ${{secrets.RAND_HOST}}
        RAND_PW: ${{secrets.RAND_PW}}
        RAND_USER: ${{secrets.RAND_USER}}
      run: |
        npm run build
        npm run deploy
